set-option -g history-limit 5000
set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u

# doom-sourcerer modeline colors
set -g status-style bg=#32353f,fg=#bbc2cf
set -g status-left-style bg=#32353f,fg=#87ceeb
set -g status-right-style bg=#32353f,fg=#b0b4a0
set -g window-status-style bg=#222222,fg=#b0b4a0
set -g window-status-current-style bg=#32353f,fg=#faf4c6
set -g window-status-last-style bg=#222222,fg=#719611
set -g pane-border-style fg=#7a7a88
set -g pane-active-border-style fg=#87AFD7
